name: 'S3 Upload Action'
description: 'This is a GitHub Action that uploads a file to Amazon S3.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  aws-access-key-id:
    description: ''
    required: true
  aws-secret-access-key:
    description: ''
    required: true
  aws-region:
    description: ''
    required: true
  aws-bucket:
    description: ''
    required: true
  file-path:
    description: ''
    required: true
  destination-dir:
    description: ''
    required: false
  metadata:
    description: ''
    default: ''
    required: false
  content-type:
    description: ''
    default: ''
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node20'
  main: 'dist/index.js'
